apiVersion: v1
kind: Service
metadata:
  name: controller
  namespace: system
  labels:
    control-plane: controller
spec:
  type: ClusterIP
  selector:
    app: sourcer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
