# permissions for end users to view gitrepositories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitrepository-viewer-role
rules:
- apiGroups:
  - sourcer.fluxcd.io
  resources:
  - gitrepositories
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sourcer.fluxcd.io
  resources:
  - gitrepositories/status
  verbs:
  - get
