# permissions for end users to edit gitrepositories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitrepository-editor-role
rules:
- apiGroups:
  - sourcer.fluxcd.io
  resources:
  - gitrepositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sourcer.fluxcd.io
  resources:
  - gitrepositories/status
  verbs:
  - get
